name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Install sshpass
        run: sudo apt-get install sshpass
        
      - name: Deploy to DigitalOcean
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
        run: |
          sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no -r dist/* $DEPLOY_USER@$DEPLOY_HOST:/var/www/html/