name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Install sshpass
        run: sudo apt-get install sshpass
        
      - name: Deploy to Server
        env:
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
        run: |
          cd dist && tar czf ../dist.tar.gz . && cd ..
          sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no dist.tar.gz root@209.38.87.210:/var/www/html/
          sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no root@209.38.87.210 'cd /var/www/html && tar xzf dist.tar.gz && rm dist.tar.gz'